### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by T0T4R4**
- Renamed some classes without the TeamCity prefix,
- Created TeamCity API wrapper class and started to centralize calls in it,
- Created entity classes for TC Build and BuildTypes
- Rewritten logic for QueueBuild and ImportArtifact operations to increase visibility on TC activity, and simplify the usage of the extension
- Replaced ProjectName/BuildConfig names by Build configuration selection dropdown in plan Operations
- Commented the post-build VS project statements for those who don't want them,
- Added two simple cmd files to automatize manual deployment on local dev workstation (without BM)
- Enhanced information in placeholders
- Added code documentation
- A nice exception message is now thrown if connection details are not specified in plan operations
- Fixed passwords showing in clear text in plan operation connection details;
- Moved Operation Editors to dedicated folder;
- Added placeholder when missing, with clear usage instructions;
- Enhanced progress output while waiting for Teamcity build;
- Cleaned up obsolete code;
- Marked [Obsolete] some legacy code;
- Reduced code complexity/verbosity in Operations by passing Operation instance to managers;

Known Issues:
- The code is still using both Configuration Profiles (legacy) and Resource Credentials (new). The Plan operations dropdownlists gets populated from the default configuration profile at the moment, and fix is required to use the selected credential instead.
- Needs global testing, particularly around Pipeline Build Importer, and Template Variable and any sort of legacy code.
- Need to help marking obsolete/legacy code - eventually moving those old classes inside a Legacy folder...

### CODE REVIEW

**Comment by T0T4R4** [comment]
Would probably be good to have a develop branch on Inedo's side also...

**Comment by T0T4R4** [comment]
Found some problems on BM v5.2, will solve this and update repo...

**Comment by T0T4R4** [comment]
That should be fine now. Works on 5.2 and 5.3
Forgot to say that artifact name is not required in ImportArtifact plan operation. The code gets all artifacts from the specified build and upload all of them into BM.

**Comment by T0T4R4** [comment]
Added branch name to buildqueue request ! If BM release name is set to the same as the git release branch name as it shows up in Teamcity, then $ReleaseName can be used as branch name in QueueBuild or ImportArtifact plan operations. Verry Niice !

**Comment by stevedennis** [comment]
@T0T4R4 --- not sure if you saw the latest version, but we ended up incorporating a lot of these ideas, though using suggestion providers and the like (new feature in 5.4/5.5 sdks).

**Pull request closed without merging**
